import {
    FaArrowLeft,
    FaEdit,
    FaFacebook,
    FaFileImage,
    FaLink,
    FaPlus,
    FaRegCircle,
    FaShoppingCart,
    FaUser,
    FaBlog,
    FaBorderAll,
    FaShippingFast,
    FaRegEye,
    FaRegEyeSlash,
    FaChevronDown,
    FaCameraRetro,
    FaReply,
} from "react-icons/fa";
import { FaGoogle } from "react-icons/fa";
import {
    RiComputerLine,
    RiPhoneFill,
    RiProductHuntLine,
    RiTruckFill,
} from "react-icons/ri";
import {
    IoIosArrowDropdown,
    IoIosArrowDropright,
    IoIosCloseCircleOutline,
    IoIosSearch,
    IoMdCheckmarkCircleOutline,
    IoMdMail,
    IoMdRemoveCircleOutline,
    IoMdReverseCamera,
    IoMdSend,
} from "react-icons/io";
import { LuBaggageClaim } from "react-icons/lu";
import {
    FaCartArrowDown,
    FaCartPlus,
    FaEye,
    FaTty,
    FaUserCircle,
} from "react-icons/fa";
import { IoDuplicateOutline, IoHome } from "react-icons/io5";
import {
    AiFillHome,
    AiFillStar,
    AiOutlineStar,
    AiFillEye,
    AiOutlineLoading3Quarters,
    AiOutlineMenu,
    AiFillGift,
    AiFillDashboard,
    AiOutlineLike,
    AiOutlineDislike,
} from "react-icons/ai";
import { RiLogoutBoxLine } from "react-icons/ri";

import { IoMdArrowRoundForward } from "react-icons/io";
import {
    BsFillCartCheckFill,
    BsFillSuitHeartFill,
    BsInfoCircleFill,
    BsReplyFill,
    BsShieldShaded,
} from "react-icons/bs";
import { FaShareFromSquare, FaUsersGear } from "react-icons/fa6";
import { AiFillProduct } from "react-icons/ai";
import { TbPackages, TbPasswordUser } from "react-icons/tb";
import {
    MdCategory,
    MdDeleteForever,
    MdDone,
    MdMessage,
    MdNavigateNext,
    MdOutlineLocalShipping,
} from "react-icons/md";
import { GrFormPrevious } from "react-icons/gr";
import { GiConfirmed, GiPositionMarker } from "react-icons/gi";
import { BiSolidDiscount } from "react-icons/bi";
import { CiCircleInfo, CiFilter, CiSettings } from "react-icons/ci";

export default {
    FaChevronDown,
    CiCircleInfo,
    FaFileImage,
    FaFacebook,
    FaGoogle,
    FaShoppingCart,
    FaArrowLeft,
    FaUser,
    RiPhoneFill,
    IoMdMail,
    LuBaggageClaim,
    FaUserCircle,
    IoHome,
    AiFillHome,
    AiFillStar,
    AiOutlineStar,
    AiFillEye,
    BsInfoCircleFill,
    AiOutlineMenu,
    AiOutlineLoading3Quarters,
    BsFillSuitHeartFill,
    IoMdArrowRoundForward,
    BsShieldShaded,
    RiTruckFill,
    AiFillGift,
    BsReplyFill,
    FaTty,
    RiLogoutBoxLine,
    AiFillDashboard,
    FaUsersGear,
    CiFilter,
    AiFillProduct,
    TbPackages,
    IoIosArrowDropdown,
    IoIosArrowDropright,
    IoMdReverseCamera,
    FaCartArrowDown,
    BsFillCartCheckFill,
    IoIosCloseCircleOutline,
    IoMdRemoveCircleOutline,
    IoMdCheckmarkCircleOutline,
    RiProductHuntLine,
    MdCategory,
    IoIosSearch,
    FaEye,
    AiOutlineLike,
    AiOutlineDislike,
    FaShareFromSquare,
    FaCartPlus,
    FaEdit,
    MdDeleteForever,
    MdNavigateNext,
    GrFormPrevious,
    FaPlus,
    FaRegCircle,
    FaBlog,
    MdDone,
    RiComputerLine,
    FaLink,
    GiConfirmed,
    BiSolidDiscount,
    GiPositionMarker,
    MdMessage,
    TbPasswordUser,
    FaBorderAll,
    FaShippingFast,
    FaRegEye,
    FaRegEyeSlash,
    IoDuplicateOutline,
    FaCameraRetro,
    IoMdSend,
    FaReply,
    CiSettings,
};
